package migration

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"golang.org/x/tools/go/packages"
	"gorm.io/cli/gorm/internal/project"
)

type modelStruct struct {
	PackagePath string
	TypeName    string
}

type diffImport struct {
	Alias string
	Path  string
}

type diffTarget struct {
	Alias    string
	TypeName string
}

type diffTemplateData struct {
	Imports []diffImport
	Targets []diffTarget
}

const diffHelperFile = "gorm_generated_diff_models_helper.go"

func (mgr Manager) generateDiffFile() (string, error) {
	structs, err := collectModelStructs(mgr.ModelsDir)
	if err != nil {
		return "", err
	}
	data := buildDiffTemplateData(structs)
	source, err := renderDiffFile(data)
	if err != nil {
		return "", err
	}
	migrationsDir := project.ResolveRootPath(mgr.MigrationsDir)
	if err := os.MkdirAll(migrationsDir, 0o755); err != nil {
		return "", fmt.Errorf("prepare migrations dir: %w", err)
	}
	path := filepath.Join(migrationsDir, diffHelperFile)
	return path, os.WriteFile(path, []byte(source), 0o644)
}

func collectModelStructs(modelsDir string) ([]modelStruct, error) {
	root := project.Root()
	if root == "" {
		return nil, fmt.Errorf("unable to determine project root")
	}
	dir := project.ResolveRootPath(modelsDir)
	if info, err := os.Stat(dir); err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("stat models dir: %w", err)
	} else if !info.IsDir() {
		return nil, fmt.Errorf("models directory must be a folder: %s", dir)
	}
	rel, err := filepath.Rel(root, dir)
	if err != nil {
		return nil, fmt.Errorf("models directory must reside within the module root: %w", err)
	}
	rel = filepath.ToSlash(rel)
	pattern := "./" + rel
	if rel == "." {
		pattern = "./..."
	} else {
		pattern += "/..."
	}
	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedSyntax | packages.NeedFiles,
		Dir:  root,
	}
	pkgs, err := packages.Load(cfg, pattern)
	if err != nil {
		return nil, fmt.Errorf("load model packages: %w", err)
	}
	var structs []modelStruct
	seen := make(map[string]struct{})
	for _, pkg := range pkgs {
		if pkg == nil || len(pkg.Syntax) == 0 {
			continue
		}
		if strings.HasSuffix(pkg.PkgPath, ".test") {
			continue
		}
		if len(pkg.Errors) > 0 {
			return nil, fmt.Errorf("load package %s: %v", pkg.PkgPath, pkg.Errors[0])
		}
		for _, file := range pkg.Syntax {
			for _, decl := range file.Decls {
				gen, ok := decl.(*ast.GenDecl)
				if !ok || gen.Tok != token.TYPE {
					continue
				}
				for _, spec := range gen.Specs {
					ts, ok := spec.(*ast.TypeSpec)
					if !ok || !ts.Name.IsExported() {
						continue
					}
					if _, ok := ts.Type.(*ast.StructType); !ok {
						continue
					}
					name := ts.Name.Name
					key := pkg.PkgPath + "." + name
					if _, ok := seen[key]; ok {
						continue
					}
					seen[key] = struct{}{}
					structs = append(structs, modelStruct{PackagePath: pkg.PkgPath, TypeName: name})
				}
			}
		}
	}
	sort.Slice(structs, func(i, j int) bool {
		if structs[i].PackagePath == structs[j].PackagePath {
			return structs[i].TypeName < structs[j].TypeName
		}
		return structs[i].PackagePath < structs[j].PackagePath
	})
	return structs, nil
}

func buildDiffTemplateData(structs []modelStruct) diffTemplateData {
	imports := make([]diffImport, 0, len(structs))
	targets := make([]diffTarget, 0, len(structs))
	aliasMap := make(map[string]string)
	for _, st := range structs {
		alias, ok := aliasMap[st.PackagePath]
		if !ok {
			alias = fmt.Sprintf("pkg%d", len(aliasMap))
			aliasMap[st.PackagePath] = alias
			imports = append(imports, diffImport{Alias: alias, Path: st.PackagePath})
		}
		targets = append(targets, diffTarget{Alias: alias, TypeName: st.TypeName})
	}
	return diffTemplateData{Imports: imports, Targets: targets}
}

func renderDiffFile(data diffTemplateData) (string, error) {
	var buf bytes.Buffer
	if err := diffFileTemplate.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("render diff helper: %w", err)
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return "", fmt.Errorf("format diff helper: %w", err)
	}
	return string(formatted), nil
}

var diffFileTemplate = template.Must(template.New("diff-helper").Parse(`// Code generated by gorm migrate diff; DO NOT EDIT.
package main

import (
    "gorm.io/cli/gorm/migration"
    {{- range .Imports }}
    {{ .Alias }} "{{ .Path }}"
    {{- end }}
)

func init() {
    {{- if .Targets }}
    migration.RegisterDiffModels(
        {{- range .Targets }}
        &{{ .Alias }}.{{ .TypeName }}{},
        {{- end }}
    )
    {{- else }}
    migration.RegisterDiffModels()
    {{- end }}
}
`))
