// Code generated by gorm migrate reflect

package models

import "time"

type MigPostgresCompany struct {
	ID           int64     `gorm:"primaryKey;column:id"`
	Code         string    `gorm:"column:code"`
	CompanyName  string    `gorm:"column:name" json:"company_name"`
	FoundedYear  int       `gorm:"column:founded_year"`
	MetadataJSON []byte    `gorm:"column:metadata"`
	CreatedAt    time.Time `gorm:"column:created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at"`
}

func (MigPostgresCompany) TableName() string {
	return "mig_postgres_companies"
}

type MigPostgresEmployee struct {
	ID           int64      `gorm:"primaryKey;column:id"`
	CompanyRefID int64      `gorm:"column:company_id"`
	FullName     string     `gorm:"column:full_name"`
	Role         string     `gorm:"column:role"`
	MetadataBlob []byte     `gorm:"column:metadata"`
	Salary       float64    `gorm:"column:salary"`
	HiredAt      time.Time  `gorm:"column:hired_at"`
	DepartedAt   *time.Time `gorm:"column:departed_at"`
}

func (MigPostgresEmployee) TableName() string {
	return "mig_postgres_employees"
}
