// Code generated by gorm migrate gen model; DO NOT EDIT.
// Table: mig_mysql_types
package models

import (
	"time"
)

type MigMysqlType struct {
	ID            uint64    `gorm:"primaryKey;column:id"`
	TinySigned    int8      `gorm:"column:tiny_signed"`
	TinyUnsigned  uint8     `gorm:"column:tiny_unsigned"`
	SmallSigned   int16     `gorm:"column:small_signed"`
	SmallUnsigned uint16    `gorm:"column:small_unsigned"`
	IntSigned     int32     `gorm:"column:int_signed"`
	IntUnsigned   uint32    `gorm:"column:int_unsigned"`
	BigSigned     int64     `gorm:"column:big_signed"`
	FloatCol      float32   `gorm:"column:float_col"`
	DoubleCol     float64   `gorm:"column:double_col"`
	CharCol       string    `gorm:"column:char_col"`
	TextCol       string    `gorm:"column:text_col"`
	BlobCol       []byte    `gorm:"column:blob_col"`
	BinaryCol     []byte    `gorm:"column:binary_col"`
	CreatedAt     time.Time `gorm:"column:created_at"`
}

func (MigMysqlType) TableName() string {
	return "mig_mysql_types"
}
