version: "3.9"

services:
  mysql:
    image: 'mysql:latest'
    ports:
      - "127.0.0.1:9910:3306"
    environment:
      - MYSQL_DATABASE=gorm
      - MYSQL_USER=gorm
      - MYSQL_PASSWORD=gorm
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
