// Code generated by gorm migrate reflect

package models

import "time"

type MigPostgresCompany struct {
	ID           int64     `gorm:"primaryKey;column:id;size:64;not null"`
	Code         string    `gorm:"column:code;type:text;size:9223372036854775807;not null"`
	CompanyName  string    `gorm:"column:name;type:text;size:9223372036854775807;not null" json:"company_name"`
	FoundedYear  int       `gorm:"column:founded_year;size:32;not null"`
	MetadataJSON []byte    `gorm:"column:metadata;type:jsonb;not null"`
	CreatedAt    time.Time `gorm:"column:created_at;size:64;not null"`
	UpdatedAt    time.Time `gorm:"column:updated_at;size:64;not null"`
}

func (MigPostgresCompany) TableName() string {
	return "mig_postgres_companies"
}

type MigPostgresEmployee struct {
	ID           int64      `gorm:"primaryKey;column:id;size:64;not null"`
	CompanyRefID int64      `gorm:"column:company_id;size:64;not null"`
	FullName     string     `gorm:"column:full_name;type:text;size:9223372036854775807;not null"`
	Role         string     `gorm:"column:role;type:text;size:9223372036854775807;not null"`
	MetadataBlob []byte     `gorm:"column:metadata;type:jsonb;not null"`
	Salary       float64    `gorm:"column:salary;precision:12;scale:2;not null"`
	HiredAt      time.Time  `gorm:"column:hired_at;size:64;not null"`
	DepartedAt   *time.Time `gorm:"column:departed_at;size:64"`
}

func (MigPostgresEmployee) TableName() string {
	return "mig_postgres_employees"
}
