// Code generated by gorm migrate gen model; DO NOT EDIT.
// Table: mig_sqlite_types
package models

import (
	"time"
)

type MigSqliteType struct {
	ID        int64     `gorm:"primaryKey;column:id"`
	Flag      bool      `gorm:"column:flag"`
	Quantity  int64     `gorm:"column:quantity"`
	Ratio     float64   `gorm:"column:ratio"`
	Payload   []byte    `gorm:"column:payload"`
	Note      string    `gorm:"column:note"`
	CreatedAt time.Time `gorm:"column:created_at"`
}

func (MigSqliteType) TableName() string {
	return "mig_sqlite_types"
}
