// Code generated by gorm migrate reflect

package models

import (
	"database/sql"
	"time"
)

type EmployeeProfile struct {
	ID           uint64         `gorm:"primaryKey;column:id"`
	EmployeeID   uint64         `gorm:"column:employee_id"`
	Phone        sql.NullString `gorm:"column:phone"`
	AvatarURL    string         `gorm:"column:avatar_url"`
	MetadataJSON []byte         `gorm:"column:metadata"`
	CreatedAt    time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at" json:"updated_at"`
}

func (EmployeeProfile) TableName() string {
	return "employee_profiles"
}
