// Code generated by gorm migrate reflect

package hr

import (
	"database/sql"
	"time"
)

type EmployeeProfile struct {
	ID           uint64         `gorm:"primaryKey;column:id;not null"`
	EmployeeID   uint64         `gorm:"column:employee_id;not null"`
	Phone        sql.NullString `gorm:"column:phone;size:32"`
	AvatarURL    string         `gorm:"column:avatar_url;size:255;not null"`
	MetadataJSON []byte         `gorm:"column:metadata;type:json;not null"`
	CreatedAt    time.Time      `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at;not null" json:"updated_at"`
}

func (EmployeeProfile) TableName() string {
	return "employee_profiles"
}
