// Code generated by gorm migrate gen model; DO NOT EDIT.
// Tables: mig_mysql_companies, mig_mysql_employees
package models

import "time"

type MigMysqlCompany struct {
	ID           uint64    `gorm:"primaryKey;column:id"`
	Code         string    `gorm:"column:code"`
	CompanyName  string    `gorm:"column:name" json:"company_name"`
	FoundedYear  int       `gorm:"column:founded_year"`
	MetadataJSON []byte    `gorm:"column:metadata"`
	CreatedAt    time.Time `gorm:"column:created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at"`
}

func (MigMysqlCompany) TableName() string {
	return "mig_mysql_companies"
}

type MigMysqlEmployee struct {
	ID           uint64     `gorm:"primaryKey;column:id"`
	CompanyRefID uint64     `gorm:"column:company_id"`
	FullName     string     `gorm:"column:full_name"`
	Role         string     `gorm:"column:role"`
	MetadataBlob []byte     `gorm:"column:metadata"`
	Salary       float64    `gorm:"column:salary"`
	HiredAt      time.Time  `gorm:"column:hired_at"`
	DepartedAt   *time.Time `gorm:"column:departed_at"`
}

func (MigMysqlEmployee) TableName() string {
	return "mig_mysql_employees"
}
