package templates

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"text/template"
)

// RunnerTemplate renders the main.go runner file for migrations.
var RunnerTemplate = template.Must(template.New("runner").Parse(runnerTemplateText))

const runnerTemplateText = `package main

import (
	"gorm.io/cli/gorm/migration"
	"gorm.io/gorm"
)

var (
	DB         *gorm.DB
	migrations []migration.Migration
	// tablesRules defines the configuration for model reflection.
	// Each rule matches tables using shell-style patterns.
	tablesRules = []migration.TableRule{
		// {
		// 	 Pattern: "users",
		// 	 Config: migration.TableConfig{
		// 		OutputPath: "internal/models/user.go",
		// 		FieldRules: []migration.FieldRule{
		// 			{Pattern: "name", FieldName: "FullName", Tags: map[string]string{"json": "{{"{{"}}.DBName{{"}}"}}"}},
		// 		},
		// 	 },
		// },
		// {
		// 	Pattern: "audit_*",
		// 	Exclude: true,
		// },
	}
)

func register(m migration.Migration) {
	migrations = append(migrations, m)
}

func main() {
	migration.New(migration.Config{
		ModelsDir:     {{printf "%q" .ModelsDir}},
		MigrationsDir: {{printf "%q" .MigrationsDir}},
		TableRules:    tablesRules,
	}, migration.WithDBAdapter(DB)).Run(migrations)
}
`

// MigrationTemplate renders a migration file.
var MigrationTemplate = template.Must(template.New("migration").Parse(migrationTemplateText))

const migrationTemplateText = `package main

import (
	"gorm.io/cli/gorm/migration"
	"gorm.io/gorm"
)

func init() {
	register(migration.Migration{
		Name: "{{.Name}}",
		Up: func(tx *gorm.DB) error {
			// TODO: implement forward migration logic
			return nil
		},
		Down: func(tx *gorm.DB) error {
			// TODO: implement rollback logic
			return nil
		},
	})
}
`

// ModelFileTemplate renders a complete model file with package and imports.
var ModelFileTemplate = template.Must(template.New("model").Parse(modelFileTemplateText))

const modelFileTemplateText = `// Code generated by gorm migrate reflect

package {{.Pkg}}
{{if .Imports}}
import (
{{- range .Imports }}
	"{{.}}"
{{- end }}
)
{{end}}

{{.Struct}}
`

// ModelStructTemplate renders just the struct definition.
var ModelStructTemplate = template.Must(template.New("modelStruct").Parse(modelStructTemplateText))

const modelStructTemplateText = `type {{.StructName}} struct {
{{.Fields}}
}

func ({{.StructName}}) TableName() string {
	return "{{.Table}}"
}
`

// DiffHelperTemplate renders the generated diff helper file.
var DiffHelperTemplate = template.Must(template.New("diff-helper").Parse(diffHelperTemplateText))

const diffHelperTemplateText = `// Code generated by gorm migrate diff; DO NOT EDIT.
package main

import (
	"gorm.io/cli/gorm/migration"
	{{- range .Imports }}
	{{ .Alias }} "{{ .Path }}"
	{{- end }}
)

func init() {
	{{- if .Targets }}
	migration.RegisterDiffModels(
		{{- range .Targets }}
		&{{ .Alias }}.{{ .TypeName }}{},
		{{- end }}
	)
	{{- else }}
	migration.RegisterDiffModels()
	{{- end }}
}
`

// RenderModelFile renders a complete model file with formatting.
func RenderModelFile(pkg, table, structName, fields string, imports []string) (string, error) {
	var buf bytes.Buffer
	sort.Strings(imports)

	structSrc, err := RenderModelStruct(structName, table, fields)
	if err != nil {
		return "", err
	}

	data := struct {
		Pkg     string
		Struct  string
		Imports []string
	}{
		Pkg:     pkg,
		Struct:  structSrc,
		Imports: imports,
	}

	if err := ModelFileTemplate.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("execute model file template: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// Return unformatted if formatting fails
		return buf.String(), nil
	}

	return string(formatted), nil
}

// RenderModelStruct renders just the struct definition.
func RenderModelStruct(structName, table, fields string) (string, error) {
	var buf bytes.Buffer

	data := struct {
		StructName string
		Table      string
		Fields     string
	}{
		StructName: structName,
		Table:      table,
		Fields:     fields,
	}

	if err := ModelStructTemplate.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("execute model struct template: %w", err)
	}

	return buf.String(), nil
}

// RenderMigrationFile renders a migration file.
func RenderMigrationFile(name string) (string, error) {
	var buf bytes.Buffer

	data := struct{ Name string }{Name: name}

	if err := MigrationTemplate.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("execute migration template: %w", err)
	}

	return buf.String(), nil
}

// RenderDiffFile renders the diff helper file.
func RenderDiffFile(data interface{}) (string, error) {
	var buf bytes.Buffer

	if err := DiffHelperTemplate.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("execute diff helper template: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return "", fmt.Errorf("format diff helper: %w", err)
	}

	return string(formatted), nil
}
