package runtime

import (
	"fmt"
	"strings"
)

func renderModelFile(pkg, table, structName, snippet string) string {
	builder := &strings.Builder{}
	fmt.Fprintf(builder, "// Code generated by gorm migrate gen model; DO NOT EDIT.\n")
	fmt.Fprintf(builder, "// Table: %s\n", table)
	if snippet != "" {
		fmt.Fprintf(builder, "// Schema: %s\n", snippet)
	}
	fmt.Fprintf(builder, "package %s\n\n", pkg)
	fmt.Fprintf(builder, "type %s struct {\n\t// TODO: add fields mapped from %s\n}\n", structName, table)
	return builder.String()
}

func renderMigrationFile(name string) string {
	return fmt.Sprintf(`package main

import (
    "gorm.io/cli/gorm/migration/runtime"
    "gorm.io/gorm"
)

func init() {
    if err := register(runtime.Migration{
        Name: "%s",
        Up: func(tx *gorm.DB) error {
            // TODO: implement forward migration logic
            return nil
        },
        Down: func(tx *gorm.DB) error {
            // TODO: implement rollback logic
            return nil
        },
    }); err != nil {
        panic(err)
    }
}
`, name)
}

func slugify(value string) string {
	value = strings.ToLower(value)
	var b strings.Builder
	b.Grow(len(value))
	prevDash := false
	for _, r := range value {
		if r >= 'a' && r <= 'z' || r >= '0' && r <= '9' {
			b.WriteRune(r)
			prevDash = false
			continue
		}
		if !prevDash {
			b.WriteByte('_')
			prevDash = true
		}
	}
	out := strings.Trim(b.String(), "_")
	if out == "" {
		return "migration"
	}
	return out
}
