package adapter

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"golang.org/x/tools/go/packages"
	"gorm.io/cli/gorm/internal/project"
)

const diffHelperFile = "gorm_generated_diff_models_helper.go"

type modelStruct struct {
	PackagePath string
	TypeName    string
}

type diffImport struct {
	Alias string
	Path  string
}

type diffTarget struct {
	Alias    string
	TypeName string
}

type diffTemplateData struct {
	Imports []diffImport
	Targets []diffTarget
}

func (a *DBAdapter) renderDiffHelper(w io.Writer) error {
	structs, err := a.collectDiffModelStructs()
	if err != nil {
		return err
	}
	source, err := renderDiffFile(structs)
	if err != nil {
		return err
	}
	if w == nil {
		w = os.Stdout
	}
	_, err = io.WriteString(w, source)
	return err
}

func (a *DBAdapter) collectDiffModelStructs() ([]modelStruct, error) {
	root := project.Root()
	if root == "" {
		return nil, fmt.Errorf("unable to determine project root")
	}
	modelsDir := project.ResolveRootPath(a.cfg.ModelsDir)
	patterns := collectModelPatterns(root, modelsDir, newTableRuleResolver(a.cfg.TableRules))
	if len(patterns) == 0 {
		return nil, nil
	}
	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedSyntax | packages.NeedFiles,
		Dir:  root,
	}
	pkgs, err := packages.Load(cfg, patterns...)
	if err != nil {
		return nil, fmt.Errorf("load model packages: %w", err)
	}
	var structs []modelStruct
	seen := make(map[string]struct{})
	for _, pkg := range pkgs {
		if pkg == nil || len(pkg.Syntax) == 0 {
			continue
		}
		if strings.HasSuffix(pkg.PkgPath, ".test") {
			continue
		}
		if len(pkg.Errors) > 0 {
			return nil, fmt.Errorf("load package %s: %v", pkg.PkgPath, pkg.Errors[0])
		}
		for _, file := range pkg.Syntax {
			for _, decl := range file.Decls {
				gen, ok := decl.(*ast.GenDecl)
				if !ok || gen.Tok != token.TYPE {
					continue
				}
				for _, spec := range gen.Specs {
					ts, ok := spec.(*ast.TypeSpec)
					if !ok || !ts.Name.IsExported() {
						continue
					}
					if _, ok := ts.Type.(*ast.StructType); !ok {
						continue
					}
					key := pkg.PkgPath + "." + ts.Name.Name
					if _, exists := seen[key]; exists {
						continue
					}
					seen[key] = struct{}{}
					structs = append(structs, modelStruct{PackagePath: pkg.PkgPath, TypeName: ts.Name.Name})
				}
			}
		}
	}
	sort.Slice(structs, func(i, j int) bool {
		if structs[i].PackagePath == structs[j].PackagePath {
			return structs[i].TypeName < structs[j].TypeName
		}
		return structs[i].PackagePath < structs[j].PackagePath
	})
	return structs, nil
}

func collectModelPatterns(root, modelsDir string, resolver tableRuleResolver) []string {
	patterns := make(map[string]struct{})
	dirs := resolver.modelDirectories(modelsDir)
	for _, dir := range dirs {
		if rel := relativePattern(root, dir); rel != "" {
			patterns[rel] = struct{}{}
		}
	}
	if len(patterns) == 0 {
		return nil
	}
	result := make([]string, 0, len(patterns))
	for pattern := range patterns {
		result = append(result, pattern)
	}
	sort.Strings(result)
	return result
}

func relativePattern(root, path string) string {
	if path == "" {
		return ""
	}
	rel, err := filepath.Rel(root, path)
	if err != nil {
		return ""
	}
	rel = filepath.ToSlash(rel)
	if rel == "." {
		return "./..."
	}
	return "./" + strings.TrimSuffix(rel, "/") + "/..."
}

func renderDiffFile(structs []modelStruct) (string, error) {
	data := buildDiffTemplateData(structs)
	var buf bytes.Buffer
	if err := diffFileTemplate.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("render diff helper: %w", err)
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return "", fmt.Errorf("format diff helper: %w", err)
	}
	return string(formatted), nil
}

func buildDiffTemplateData(structs []modelStruct) diffTemplateData {
	imports := make([]diffImport, 0, len(structs))
	targets := make([]diffTarget, 0, len(structs))
	aliasMap := make(map[string]string)
	for _, st := range structs {
		alias, ok := aliasMap[st.PackagePath]
		if !ok {
			alias = fmt.Sprintf("pkg%d", len(aliasMap))
			aliasMap[st.PackagePath] = alias
			imports = append(imports, diffImport{Alias: alias, Path: st.PackagePath})
		}
		targets = append(targets, diffTarget{Alias: alias, TypeName: st.TypeName})
	}
	return diffTemplateData{Imports: imports, Targets: targets}
}

var diffFileTemplate = template.Must(template.New("diff-helper").Parse(`// Code generated by gorm migrate diff; DO NOT EDIT.
package main

import (
    "gorm.io/cli/gorm/migration"
    {{- range .Imports }}
    {{ .Alias }} "{{ .Path }}"
    {{- end }}
)

func init() {
    {{- if .Targets }}
    migration.RegisterDiffModels(
        {{- range .Targets }}
        &{{ .Alias }}.{{ .TypeName }}{},
        {{- end }}
    )
    {{- else }}
    migration.RegisterDiffModels()
    {{- end }}
}
`))
