package adapter

import (
	"bytes"
	"go/format"
	"sort"
	"strings"
	"text/template"
)

func renderModelFile(pkg, table, structName, fields string, imports []string) string {
	var buf bytes.Buffer
	sort.Strings(imports)
	structSrc := renderModelStruct(structName, table, fields)
	_ = modelFileTemplate.Execute(&buf, struct {
		Pkg     string
		Struct  string
		Imports []string
	}{Pkg: pkg, Struct: structSrc, Imports: imports})
	formatted, err := format.Source(buf.Bytes())
	if err == nil {
		return string(formatted)
	}
	return buf.String()
}

func renderModelStruct(structName, table, fields string) string {
	var buf bytes.Buffer
	_ = modelStructTemplate.Execute(&buf, struct {
		StructName string
		Table      string
		Fields     string
	}{StructName: structName, Table: table, Fields: fields})
	return buf.String()
}

func renderMigrationFile(name string) string {
	var buf bytes.Buffer
	_ = migrationFileTemplate.Execute(&buf, struct{ Name string }{Name: name})
	return buf.String()
}

var migrationFileTemplate = template.Must(template.New("migration").Parse(`package main

import (
	"gorm.io/cli/gorm/migration"
	"gorm.io/gorm"
)

func init() {
	register(migration.Migration{
		Name: "{{.Name}}",
		Up: func(tx *gorm.DB) error {
			// TODO: implement forward migration logic
			return nil
		},
		Down: func(tx *gorm.DB) error {
			// TODO: implement rollback logic
			return nil
		},
	})
}
`))

var modelFileTemplate = template.Must(template.New("model").Parse(`// Code generated by gorm migrate reflect

package {{.Pkg}}
{{if .Imports}}
import (
{{- range .Imports }}
	"{{.}}"
{{- end }}
)
{{end}}

{{.Struct}}
`))

var modelStructTemplate = template.Must(template.New("modelStruct").Parse(`type {{.StructName}} struct {
{{.Fields}}
}

func ({{.StructName}}) TableName() string {
	return "{{.Table}}"
}
`))

type tagContext struct {
	Table  string
	Name   string
	DBName string
	DBType string
}

func renderTagValue(tpl string, ctx tagContext) (string, error) {
	if !strings.Contains(tpl, "{{") {
		return tpl, nil
	}
	t, err := template.New("tag").Parse(tpl)
	if err != nil {
		return "", err
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, ctx); err != nil {
		return "", err
	}
	return buf.String(), nil
}
