// Code generated by gorm migrate gen model; DO NOT EDIT.
// Tables: org_companies, org_employees
package models

import (
	"database/sql"
	"time"
)

type OrgCompany struct {
	ID           sql.NullInt64  `gorm:"column:id"`
	Code         sql.NullString `gorm:"column:code"`
	CompanyName  sql.NullString `gorm:"column:name" json:"company_name"`
	FoundedYear  sql.NullInt64  `gorm:"column:founded_year"`
	MetadataBlob []byte         `gorm:"column:metadata"`
	CreatedAt    sql.NullTime   `gorm:"column:created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at"`
}

func (OrgCompany) TableName() string {
	return "org_companies"
}

type OrgEmployee struct {
	ID           sql.NullInt64   `gorm:"column:id"`
	CompanyRefID *int64          `gorm:"column:company_id"`
	FullName     sql.NullString  `gorm:"column:full_name"`
	Role         sql.NullString  `gorm:"column:role"`
	MetadataJSON []byte          `gorm:"column:metadata"`
	Salary       sql.NullFloat64 `gorm:"column:salary"`
	HiredAt      sql.NullTime    `gorm:"column:hired_at"`
	DepartedAt   sql.NullTime    `gorm:"column:departed_at"`
}

func (OrgEmployee) TableName() string {
	return "org_employees"
}
