package adapter

import (
	"bytes"
	"strings"
	"text/template"
)

func renderModelFile(pkg, table, structName, snippet string) string {
	var buf bytes.Buffer
	_ = modelFileTemplate.Execute(&buf, struct {
		Pkg        string
		Table      string
		StructName string
		Snippet    string
	}{Pkg: pkg, Table: table, StructName: structName, Snippet: snippet})
	return buf.String()
}

func renderMigrationFile(name string) string {
	var buf bytes.Buffer
	_ = migrationFileTemplate.Execute(&buf, struct{ Name string }{Name: name})
	return buf.String()
}

var migrationFileTemplate = template.Must(template.New("migration").Parse(`package main

import (
    "gorm.io/cli/gorm/migration"
    "gorm.io/gorm"
)

func init() {
    register(migration.Migration{
        Name: "{{.Name}}",
        Up: func(tx *gorm.DB) error {
            // TODO: implement forward migration logic
            return nil
        },
        Down: func(tx *gorm.DB) error {
            // TODO: implement rollback logic
            return nil
        },
    })
}
`))

var modelFileTemplate = template.Must(template.New("model").Parse(`// Code generated by gorm migrate gen model; DO NOT EDIT.
// Table: {{.Table}}
{{- if .Snippet}}
// Schema: {{.Snippet}}
{{- end}}
package {{.Pkg}}

type {{.StructName}} struct {
    // TODO: add fields mapped from {{.Table}}
}
`))

func slugify(value string) string {
	value = strings.TrimSpace(strings.ToLower(value))
	value = strings.ReplaceAll(value, " ", "_")
	value = strings.ReplaceAll(value, "-", "_")
	value = strings.Trim(value, "_")
	if value == "" {
		return "migration"
	}
	return value
}
