// Code generated by gorm migrate gen model; DO NOT EDIT.
// Table: mig_postgres_types
package models

import (
	"time"
)

type MigPostgresType struct {
	ID        int64      `gorm:"primaryKey;column:id"`
	Flag      bool       `gorm:"column:flag"`
	Counter   int16      `gorm:"column:counter"`
	Score     int32      `gorm:"column:score"`
	Balance   int64      `gorm:"column:balance"`
	Ratio     float32    `gorm:"column:ratio"`
	Price     float64    `gorm:"column:price"`
	Payload   []byte     `gorm:"column:payload"`
	Name      string     `gorm:"column:name"`
	CreatedAt time.Time  `gorm:"column:created_at"`
	ExpiresAt *time.Time `gorm:"column:expires_at"`
}

func (MigPostgresType) TableName() string {
	return "mig_postgres_types"
}
