// Code generated by gorm migrate reflect

package models

import (
	"time"
)

type Company struct {
	ID           uint64    `gorm:"primaryKey;column:id"`
	Code         string    `gorm:"column:code"`
	CompanyName  string    `gorm:"column:name" json:"company_name"`
	FoundedYear  int32     `gorm:"column:founded_year"`
	MetadataJSON []byte    `gorm:"column:metadata"`
	CreatedAt    time.Time `gorm:"column:created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at"`
}

func (Company) TableName() string {
	return "companies"
}

type Employee struct {
	ID           uint64     `gorm:"primaryKey;column:id"`
	CompanyRefID uint64     `gorm:"column:company_id"`
	FullName     string     `gorm:"column:full_name"`
	Role         string     `gorm:"column:role" json:"role"`
	MetadataBlob []byte     `gorm:"column:metadata"`
	Salary       float64    `gorm:"column:salary"`
	HiredAt      time.Time  `gorm:"column:hired_at"`
	DepartedAt   *time.Time `gorm:"column:departed_at"`
	CreatedAt    time.Time  `gorm:"column:created_at" json:"created_at"`
	UpdatedAt    time.Time  `gorm:"column:updated_at" json:"updated_at"`
}

func (Employee) TableName() string {
	return "employees"
}

func (e Employee) GetFullName() string {
	return e.FullName
}
